### ISSUE TITLE
Get navx installed for more DIO Pins... we need more.

### ISSUE THREAD

**Issue by Michaelmvv** [AlphaKnights/2018RobotCode#2]
https://www.pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/java/

**Comment by Michaelmvv** [comment]
https://www.kauailabs.com/support/navx-mxp/kb/faq.php?id=48 update the navx

**Comment by iamgarcia** [comment]
Problem:
navX's DIO pins don't detect the switches. When all switches are supposed to return *false*, some switches return *true*. When you try to turn on/off a switch, nothing is logged into the console. We figured that the DIO pins are a bust, so what we will do is buy an adapter that enables additional DIO pins so that way we can use the switches.

**Comment by pashabou** [comment]
replaced with rev board
